### PR TITLE
Improvements from testing

### LINKED ISSUE #919: Improvements from testing
3) tenhle case by to melo ukazovat 

"undecidable" pro DQA1 protilatky ne?
Screenshot from 2022-07-15 18-00-20

zaclo to fungovat az kdyz jsem odebral vsechny z other a pak se tam zas objevily obe ty skupiny i warning:

Screenshot from 2022-07-15 18-05-44

4) bridging donor neni ab0i 

Screenshot from 2022-07-15 18-02-26

5) Alter match type logic further
- typization in split a ALL antibodies in high res positive for this split ->  currently crossmatch_level high_Res_wtih_split, newly high_Res
- typization in split and SOME antibodies in high res positive for this split -> currently crossmatch level split, newly high_res_with_split

### PR DESCRIPTION
**Pull request by kristinagalik**
Closes #919

### CODE REVIEW

**Review by kubantjan — CHANGES_REQUESTED** [review]
Why is there i change in sample_html_report.html?
- could you add a test testing the newly added thing with the other typization group?

**Comment by kristinagalik** [comment]
@kubantjan changes in html report are because of undecidable antibodies 
image
changed to this:
image
etc...

**Comment by kristinagalik** [comment]
> * could you add a test testing the newly added thing with the other typization group?

not sure what exactly do you mean? @kubantjan

**Comment by kubantjan** [comment]
> > * could you add a test testing the newly added thing with the other typization group?
> 
> not sure what exactly do you mean? @kubantjan
> 
> there are tests for undecidable group

so before you did not get undecidable antibodies unless the group "other" was completely empty. But no test has identified this issue. 

So add test that would have been failing before, but is not failing now anymore :

**Review by kubantjan — APPROVED** [review]

**Pull request merged**
